apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
spec:
  storageClassName: hostpath-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Should match the capacity in the PersistentVolume
